"""Evaluate saved RAFT predictions with LlamaIndex RAG evaluators."""

import argparse
import logging
import os
from pathlib import Path
from typing import Any

import pandas as pd
from azure.identity import AzureCliCredential
from dotenv import load_dotenv
from tqdm import tqdm

from llama_index.core.evaluation import (
    CorrectnessEvaluator,
    FaithfulnessEvaluator,
    RelevancyEvaluator,
)
from llama_index.llms.azure_openai import AzureOpenAI

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)
logging.getLogger("httpx").setLevel(logging.WARNING)

_ad_token = AzureCliCredential().get_token(
    "https://cognitiveservices.azure.com/.default"
).token


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate RAFT predictions with LlamaIndex evaluators"
    )
    parser.add_argument(
        "--predictions",
        default="./output/raft_predictions.csv",
        help="Path to predictions CSV generated by RAFT_Inference.py",
    )
    parser.add_argument(
        "--eval-model",
        default=os.getenv("AZURE_OPENAI_GPT4O_DEPLOYMENT", "gpt-4o"),
        help="Azure OpenAI deployment name for evaluation",
    )
    parser.add_argument(
        "--eval-model-name",
        default=os.getenv("AZURE_OPENAI_EVAL_MODEL_NAME", "gpt-4o"),
        help="OpenAI model identifier for tokenization, e.g. gpt-4o",
    )
    parser.add_argument(
        "--output",
        default="./output/raft_llama_eval_results.csv",
        help="Path to detailed evaluation CSV",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional max number of prediction rows",
    )
    return parser.parse_args()


def build_llm(deployment: str, model_name: str) -> AzureOpenAI:
    endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
    api_version = os.getenv("AZURE_OPENAI_API_VERSION")

    if not endpoint or not api_version:
        raise ValueError(
            "Missing AZURE_OPENAI_ENDPOINT or AZURE_OPENAI_API_VERSION in environment."
        )

    return AzureOpenAI(
        model=model_name,
        deployment_name=deployment,
        api_key=_ad_token,
        azure_endpoint=endpoint,
        api_version=api_version,
        use_azure_ad=True,
        azure_ad_token_provider=lambda: _ad_token,
        temperature=0,
    )


def load_predictions(path: str, limit: int | None = None) -> list[dict[str, Any]]:
    dataframe = pd.read_csv(path).fillna("")
    if limit is not None:
        dataframe = dataframe.head(limit)

    required_columns = {"question", "context", "model_answer", "reference_answer"}
    missing_columns = required_columns.difference(dataframe.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise ValueError(f"Predictions file is missing required column(s): {missing}")

    records = dataframe.to_dict(orient="records")
    log.info("Loaded %d prediction row(s) from %s", len(records), path)
    return records


def evaluate_one(
    faithfulness: FaithfulnessEvaluator,
    relevancy: RelevancyEvaluator,
    correctness: CorrectnessEvaluator,
    question: str,
    answer: str,
    context: str,
    reference: str,
) -> dict[str, Any]:
    faith = faithfulness.evaluate(
        query=question,
        response=answer,
        contexts=[context],
    )
    rel = relevancy.evaluate(
        query=question,
        response=answer,
        contexts=[context],
    )
    corr = correctness.evaluate(
        query=question,
        response=answer,
        reference=reference,
    )

    return {
        "faithfulness": faith.score,
        "relevancy": rel.score,
        "correctness": corr.score,
        "faithfulness_passing": faith.passing,
        "relevancy_passing": rel.passing,
        "correctness_passing": corr.passing,
        "faithfulness_feedback": faith.feedback,
        "relevancy_feedback": rel.feedback,
        "correctness_feedback": corr.feedback,
    }


def process_prediction(
    prediction: dict[str, Any],
    faithfulness: FaithfulnessEvaluator,
    relevancy: RelevancyEvaluator,
    correctness: CorrectnessEvaluator,
) -> dict[str, Any] | None:
    question = str(prediction.get("question", "")).strip()
    model_answer = str(prediction.get("model_answer", "")).strip()
    if not question or not model_answer:
        return None

    context = str(prediction.get("context", ""))
    reference = str(prediction.get("reference_answer", ""))
    eval_result = evaluate_one(
        faithfulness=faithfulness,
        relevancy=relevancy,
        correctness=correctness,
        question=question,
        answer=model_answer,
        context=context,
        reference=reference,
    )

    return {
        "model_name": str(prediction.get("model_name", "")),
        "type": str(prediction.get("type", "")),
        "question": question,
        "model_answer": model_answer,
        "reference_answer": reference,
        **eval_result,
    }


def run(args: argparse.Namespace) -> None:
    predictions = load_predictions(args.predictions, args.limit)
    if not predictions:
        raise ValueError("No prediction rows found.")

    log.info(
        "Building eval LLM (deployment=%s, model=%s)",
        args.eval_model,
        args.eval_model_name,
    )
    eval_llm = build_llm(args.eval_model, args.eval_model_name)

    faithfulness = FaithfulnessEvaluator(llm=eval_llm)
    relevancy = RelevancyEvaluator(llm=eval_llm)
    correctness = CorrectnessEvaluator(llm=eval_llm)

    rows: list[dict[str, Any]] = []
    log.info("Evaluating %d prediction row(s)", len(predictions))
    for prediction in tqdm(predictions, desc="Evaluating", unit="sample"):
        try:
            row = process_prediction(
                prediction,
                faithfulness,
                relevancy,
                correctness,
            )
        except Exception as exc:
            log.error("Prediction failed: %s", exc, exc_info=True)
            continue
        if row is not None:
            rows.append(row)

    if not rows:
        raise ValueError("No rows evaluated. Check predictions format.")

    dataframe = pd.DataFrame(rows)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    dataframe.to_csv(output_path, index=False)

    summary = {
        "faithfulness_avg": float(dataframe["faithfulness"].dropna().mean()),
        "relevancy_avg": float(dataframe["relevancy"].dropna().mean()),
        "correctness_avg": float(dataframe["correctness"].dropna().mean()),
        "faithfulness_pass_rate": float(dataframe["faithfulness_passing"].mean()),
        "relevancy_pass_rate": float(dataframe["relevancy_passing"].mean()),
        "correctness_pass_rate": float(dataframe["correctness_passing"].mean()),
    }

    print("\nLlamaIndex RAG Evaluation Summary")
    for key, value in summary.items():
        print(f"- {key}: {value:.4f}")
    print(f"\nSaved detailed results to: {output_path}")


if __name__ == "__main__":
    cli_args = parse_args()
    run(cli_args)
